name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

    steps:
    - name: create release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ github.ref }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}

  publish-linux-x64:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: publish linux-x64
      run: dotnet publish ./dotnet/CsvReader/CsvReader.csproj -r linux-x64 --self-contained true -o CsvReader-linux-x64
    - name: Zip artifact for deployment
      run: 7za a -t7z CsvReader-linux-x64.zip ./dotnet/CsvReader-linux-x64/*
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url}}
        asset_path: ./CsvReader-linux-x64.zip
        asset_name: CsvReader-linux-x64.zip
        asset_content_type: application/gzip

  publish-win10-x64:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: publish win10-x64
      run: dotnet publish ./dotnet/CsvReader/CsvReader.csproj -r win10-x64 --self-contained true -o CsvReader-win10-x64
    - name: Zip artifact for deployment
      run: 7za a -t7z CsvReader-win10-x64.zip ./dotnet/CsvReader-win10-x64/*
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url}}
        asset_path: ./CsvReader-win10-x64.zip
        asset_name: CsvReader-win10-x64.zip
        asset_content_type: application/gzip

  publish-osx-x64:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: publish osx-x64
      run: dotnet publish ./dotnet/CsvReader/CsvReader.csproj -r osx-x64 --self-contained true -o CsvReader-osx-x64
    - name: Zip artifact for deployment
      run: 7za a -t7z CsvReader-osx-x64.zip ./dotnet/CsvReader-osx-x64/*
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url}}
        asset_path: ./CsvReader-osx-x64.zip
        asset_name: CsvReader-osx-x64.zip
        asset_content_type: application/gzip

  publish-osx-arm64:
    runs-on: ubuntu-latest
    needs: create-release
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: publish osx.12-arm64
      run: dotnet publish ./dotnet/CsvReader/CsvReader.csproj -r osx.12-arm64 --self-contained true -o CsvReader-osx.12-arm64
    - name: Zip artifact for deployment
      run: 7za a -t7z CsvReader-osx.12-arm64.zip ./dotnet/CsvReader-osx.12-arm64/*
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url}}
        asset_path: ./CsvReader-osx.12-arm64.zip
        asset_name: CsvReader-osx.12-arm64.zip
        asset_content_type: application/gzip
  
